nifty200 = ['360ONE', 'ABB', 'ACC', 'APLAPOLLO', 'AUBANK', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ATGL', 'ABCAPITAL', 'ALKEM', 'AMBUJACEM', 'APOLLOHOSP', 'ASHOKLEY', 'ASIANPAINT', 'ASTRAL', 'AUROPHARMA', 'DMART', 'AXISBANK', 'BSE', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJAJHFL', 'BANKBARODA', 'BANKINDIA', 'BDL', 'BEL', 'BHARATFORG', 'BHEL', 'BPCL', 'BHARTIARTL', 'BHARTIHEXA', 'BIOCON', 'BLUESTARCO', 'BOSCHLTD', 'BRITANNIA', 'CGPOWER', 'CANBK', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL', 'CUMMINSIND', 'DLF', 'DABUR', 'DIVISLAB', 'DIXON', 'DRREDDY', 'EICHERMOT', 'ETERNAL', 'EXIDEIND', 'NYKAA', 'FEDERALBNK', 'FORTIS', 'GAIL', 'GMRAIRPORT', 'GLENMARK', 'GODFRYPHLP', 'GODREJCP', 'GODREJPROP', 'GRASIM', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HAVELLS', 'HEROMOTOCO', 'HINDALCO', 'HAL', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'POWERINDIA', 'HUDCO', 'HYUNDAI', 'ICICIBANK', 'ICICIGI', 'IDFCFIRSTB', 'IRB', 'ITCHOTELS', 'ITC', 'INDIANB', 'INDHOTEL', 'IOC', 'IRCTC', 'IRFC', 'IREDA', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'NAUKRI', 'INFY', 'INDIGO', 'JSWENERGY', 'JSWSTEEL', 'JINDALSTEL', 'JIOFIN', 'JUBLFOOD', 'KEI', 'KPITTECH', 'KALYANKJIL', 'KOTAKBANK', 'LTF', 'LICHSGFIN', 'LTIM', 'LT', 'LICI', 'LODHA', 'LUPIN', 'MRF', 'M&MFIN', 'M&M', 'MANKIND', 'MARICO', 'MARUTI', 'MFSL', 'MAXHEALTH', 'MAZDOCK', 'MOTILALOFS', 'MPHASIS', 'MUTHOOTFIN', 'NHPC', 'NMDC', 'NTPCGREEN', 'NTPC', 'NATIONALUM', 'NESTLEIND', 'OBEROIRLTY', 'ONGC', 'OIL', 'PAYTM', 'OFSS', 'POLICYBZR', 'PIIND', 'PAGEIND', 'PATANJALI', 'PERSISTENT', 'PHOENIXLTD', 'PIDILITIND', 'POLYCAB', 'PFC', 'POWERGRID', 'PREMIERENE', 'PRESTIGE', 'PNB', 'RECLTD', 'RVNL', 'RELIANCE', 'SBICARD', 'SBILIFE', 'SRF', 'MOTHERSON', 'SHREECEM', 'SHRIRAMFIN', 'ENRIN', 'SIEMENS', 'SOLARINDS', 'SONACOMS', 'SBIN', 'SAIL', 'SUNPHARMA', 'SUPREMEIND', 'SUZLON', 'SWIGGY', 'TVSMOTOR', 'TATACOMM', 'TCS', 'TATACONSUM', 'TATAELXSI', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TATATECH', 'TECHM', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TIINDIA', 'UPL', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'VMM', 'IDEA', 'VOLTAS', 'WAAREEENER', 'WIPRO', 'YESBANK', 'ZYDUSLIFE']
midcap100 = ['360ONE', 'ACC', 'APLAPOLLO', 'AUBANK', 'ATGL', 'ABCAPITAL', 'ALKEM', 'ASHOKLEY', 'ASTRAL', 'AUROPHARMA', 'BSE', 'BANKINDIA', 'BDL', 'BHARATFORG', 'BHEL', 'BHARTIHEXA', 'BIOCON', 'BLUESTARCO', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CONCOR', 'COROMANDEL', 'CUMMINSIND', 'DABUR', 'DIXON', 'EXIDEIND', 'NYKAA', 'FEDERALBNK', 'FORTIS', 'GMRAIRPORT', 'GLENMARK', 'GODFRYPHLP', 'GODREJPROP', 'HDFCAMC', 'HEROMOTOCO', 'HINDPETRO', 'POWERINDIA', 'HUDCO', 'IDFCFIRSTB', 'IRB', 'ITCHOTELS', 'INDIANB', 'IRCTC', 'IREDA', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'JUBLFOOD', 'KEI', 'KPITTECH', 'KALYANKJIL', 'LTF', 'LICHSGFIN', 'LUPIN', 'MRF', 'M&MFIN', 'MANKIND', 'MARICO', 'MFSL', 'MOTILALOFS', 'MPHASIS', 'MUTHOOTFIN', 'NHPC', 'NMDC', 'NTPCGREEN', 'NATIONALUM', 'OBEROIRLTY', 'OIL', 'PAYTM', 'OFSS', 'POLICYBZR', 'PIIND', 'PAGEIND', 'PATANJALI', 'PERSISTENT', 'PHOENIXLTD', 'POLYCAB', 'PREMIERENE', 'PRESTIGE', 'RVNL', 'SBICARD', 'SRF', 'SONACOMS', 'SAIL', 'SUPREMEIND', 'SUZLON', 'SWIGGY', 'TATACOMM', 'TATAELXSI', 'TATATECH', 'TORNTPOWER', 'TIINDIA', 'UPL', 'UNIONBANK', 'VMM', 'IDEA', 'VOLTAS', 'WAAREEENER', 'YESBANK']
smlcap100 = ['AADHARHFC', 'AARTIIND', 'ABREL', 'AEGISLOG', 'AEGISVOPAK', 'AFCONS', 'AFFLE', 'ARE&M', 'AMBER', 'ANANDRATHI', 'ANANTRAJ', 'ANGELONE', 'APTUS', 'ASTERDM', 'ATUL', 'BEML', 'BLS', 'BANDHANBNK', 'FIRSTCRY', 'BRIGADE', 'CESC', 'CGCL', 'CASTROLIND', 'CDSL', 'CHAMBLFERT', 'CHOLAHLDNG', 'CAMS', 'CREDITACC', 'CROMPTON', 'CYIENT', 'DATAPATTNS', 'DEEPAKFERT', 'DELHIVERY', 'DEVYANI', 'LALPATHLAB', 'FSL', 'FIVESTAR', 'GRSE', 'GILLETTE', 'GLAND', 'GODIGIT', 'GESHIP', 'HBLENGINE', 'HSCL', 'HINDCOPPER', 'IFCI', 'IIFL', 'IRCON', 'IEX', 'INOXWIND', 'IGIL', 'IKS', 'JBCHEPHARM', 'JBMA', 'JINDALSAW', 'JWL', 'JYOTICNC', 'KAJARIACER', 'KPIL', 'KARURVYSYA', 'KAYNES', 'KEC', 'KFINTECH', 'LAURUSLABS', 'MGL', 'MANAPPURAM', 'MRPL', 'MCX', 'NATCOPHARM', 'NBCC', 'NCC', 'NH', 'NAVINFLUOR', 'NEULANDLAB', 'NEWGEN', 'NUVAMA', 'OLAELEC', 'PCBL', 'PGEL', 'PNBHOUSING', 'PPLPHARMA', 'POONAWALLA', 'RADICO', 'REDINGTON', 'RPOWER', 'SAGILITY', 'SHYAMMETL', 'SIGNATURE', 'STARHEALTH', 'SWANCORP', 'TATACHEM', 'TEJASNET', 'RAMCOCEM', 'TRIDENT', 'TRITURBINE', 'WELCORP', 'WHIRLPOOL', 'WOCKPHARMA', 'ZENTEC', 'ZENSARTECH']
#print(f"All = {sorted(list(set(nifty200) | set(midcap100)  | set(smlcap100)))}")

AllList = sorted(list(set(nifty200) | set(midcap100)  | set(smlcap100)))

import datetime as dt
import yfinance as yf
import pandas as pd
from nsepython import equity_history

end_date = dt.date.today() + dt.timedelta(days=1)
start_date = end_date - dt.timedelta(days=365)

def win_eq_func(sym):
    df = yf.download(sym + ".NS", start=start_date, end=end_date, auto_adjust=True, progress=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [col[0] for col in df.columns]
    df = df.reset_index()
    df['Close'] = df['Close'].round(2)
    return df[['Date', 'Close']]

def pydroid_eq_func(sym):
    df = equity_history(symbol=sym, series="EQ",
                        start_date=start_date.strftime("%d-%m-%Y"),
                        end_date=end_date.strftime("%d-%m-%Y"))
    df.rename(columns={"CH_TIMESTAMP": "Date", "CH_CLOSING_PRICE": "Close"}, inplace=True)
    df.sort_values(by='Date', inplace=True)
    return df[['Date', 'Close']]
    #return df[['Date', 'Close', 'CH_LAST_TRADED_PRICE']]
    #df['Date'] = pd.to_datetime(df['CH_TIMESTAMP']).dt.date
    #df.set_index('Date', inplace=True)    